app/models/post.py
from ..extensions import db
from datetime import datetime

class Post(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    teacher = db.Column(db.String(250))
    student = db.Column(db.String(250))
    subject = db.Column(db.String(250))
    date = db.Column(db.DateTime, default=datetime.utcnow)

app/models/user.py
from ..extensions import db
from datetime import datetime


class User(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    status = db.Column(db.String(50), default='user')
    avatar = db.Column(db.String(200))
    name = db.Column(db.String(50))
    login = db.Column(db.String(50))
    password = db.Column(db.String(50))
    date = db.Column(db.DateTime, default=datetime.utcnow)

app/forms.py
from flask_wtf import FlaskForm
from wtforms import FileField, StringField, PasswordField, BooleanField , SubmitField, ValidationError
from flask_wtf.file import FileAllowed, DataRequired
from wtforms.validators import DataRequired, Length, EqualTo
from .models.user import User

class RegistrationFrom(FlaskForm):
    name = StringField('ФИО', validators=[DataRequired(), Length(min=2, max=100)])
    login = StringField('Login', validators=[DataRequired(), Length(min=2, max=200)],render_kw={
        'class': 'form-control',
        'placeholder': 'Login'
    })
    password = PasswordField('Password', validators=[DataRequired()])
    confirm_password = PasswordField('Confirm password', validators=[DataRequired(), EqualTo('password')])
    avatar = FileField('Upload your photo', validators=[FileAllowed(['jpg', 'jpeg', 'png'])])
    submit = SubmitField('Log out')
    
    def validate_login(self, login):
        user = User.query.filter_by(login=login.data).first()
        if user:
            raise ValidationError('Данное имя пользователя уже занято!')

class LoginForm(FlaskForm):
    """Form to log in"""
    login = StringField('Login', validators=[DataRequired(), Length(min=2, max=20)])
    password = PasswordField('Password', validators=[DataRequired()])
    remember = BooleanField("Remember me")
    submit = SubmitField("Log in")

app/__init__.py
from flask import Flask
from .extensions import db
from .extensions import migratre
from .config import Config
from .routes.user import user
from .routes.post import post


# точка входа
def create_app(config_class=Config):
    app = Flask(__name__)
    app.config.from_object(config_class)

    app.register_blueprint(user)
    app.register_blueprint(post)

    db.init_app(app)
    migratre.init_app(app, db)

    with app.app_context():
        db.create_all()
    return app

app/routes/post.py
from flask import Blueprint, render_template, request, redirect
import re
from ..extensions import db
from ..models.post import Post

post = Blueprint('post', __name__)

@post.route('/', methods=['POST', 'GET'])
def all():
    posts = Post.query.order_by(Post.date).all()
    return render_template('post/all.html', posts=posts)


@post.route('/post/create', methods=['POST', 'GET'])
def create():
    if request.method == 'POST':
        teacher = request.form['teacher']
        subject = request.form['subject']
        student = request.form['student']

        post = Post(teacher=teacher, subject=subject, student=student)

        try:
            db.session.add(post)
            db.session.commit()
            return redirect('/')
        except Exception as e:
            print(str(e))

        return "some"
    else:
        return render_template('post/create.html')
    

@post.route('/post/<int:id>/update', methods=['POST', 'GET'])
def update(id):
    post = Post.query.get(id)
    if request.method == 'POST':
        post.teacher = request.form.get('teacher')
        post.subject = request.form.get('subject')
        post.student = request.form.get('student')
        try:
            db.session.commit()
            return redirect('/')
        except Exception as e:
            print(str(e))
    else:
        return render_template('post/update.html', post=post)


@post.route('/post/<int:id>/delete', methods=['POST', 'GET'])
def delete(id):
    post = Post.query.get(id)
    try:
        db.session.delete(post)
        db.session.commit()
        return redirect('/')
    except Exception as e:
        print(str(e))
        return str(e)

app/routes/user.py
from flask import Blueprint, redirect, render_template, flash, url_for
from ..extensions import db, bcrypt
from ..models.user import User
from ..forms import RegistrationFrom, LoginForm
from ..functions import save_picture

user = Blueprint('user', __name__)

@user.route('/user/register')
def register():
    form = RegistrationFrom()
    if form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        avatar_filename = save_picture(form.avatar.data)
        user = User(name=form.name.data, login=form.login.data, avatar=avatar_filename, password=hashed_password)
        db.session.add(user)
        db.session.commit()
        flash(f"Добро пожаловать, {form.login.data}! Вы зарегистрированы!", "success")
        return redirect(url_for('user.login'))
    else:
        flash(f"При регистрации произошла ошибка", "danger")
        print('Error while registration')
    return render_template('user/register.html', form=form)


@user.route('/user/login')
def login():
    form = LoginForm()
 
    return render_template('user/login.html', form=form)

app/templates/main/_flash.html
    <!-- FLASH messages-->
    {% with messages = get_flashed_messages(with_categories=true) %}
        {% if messages %}
            {% for category, message in messages %}
                <div class="alert alert-{{ category }}">
                    {{ message }}
                </div> 
            {% endfor %}
        {% endif %}
    {% endwith %}
    <!-- FLASH messages-->

app/templates/main/_footer.html
<ul class="nav justify-content-center border-bottom pb-3 mb-3">
    <li class="nav-item"><a href="#" class="nav-link px-2">Home</a></li>
    <li class="nav-item"><a href="#" class="nav-link px-2">Features</a></li>
    <li class="nav-item"><a href="#" class="nav-link px-2">Pricing</a></li>
    <li class="nav-item"><a href="#" class="nav-link px-2">FAQs</a></li>
    <li class="nav-item"><a href="#" class="nav-link px-2">About</a></li>
</ul>
<p class="text-center">© 2025 Company, Inc</p>

app/templates/main/_header.html
<div class="d-flex flex-wrap align-items-center justify-content-center justify-content-lg-start"> 
    <a href="{{ url_for('post.all') }}" class="d-flex align-items-center mb-2 mb-lg-0 text-white text-decoration-none"> 
   <img class="header__img" src="{{ url_for('static', filename='img/fox-svgrepo-com.svg')}}" alt="fox">
    </a>
    <ul class="nav col-12 col-lg-auto me-lg-auto mb-2 justify-content-center mb-md-0">
        <li><a href="{{ url_for('post.all') }}" class="nav-link px-2 text-secondary">Главная</a></li>
        <li><a href="{{ url_for('post.create') }}" class="nav-link px-2 text-secondary">Добавить тему</a></li>
        
        <!-- <li><a href="#" class="nav-link px-2 text-white">Features</a></li>
        <li><a href="#" class="nav-link px-2 text-white">Pricing</a></li>
        <li><a href="#" class="nav-link px-2 text-white">FAQs</a></li>
        <li><a href="#" class="nav-link px-2 text-white">About</a></li> -->
    </ul>


    <div class="text-end"> 
        <a href="{{ url_for('user.login') }} class="btn btn-outline-light me-2">Войти</button> 
        <button type="button" class="btn btn-warning">
            <a href="{{ url_for('user.register') }}">Регистрация</a>
        </button> </div>
</div>

app/templates/main/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="{{url_for('static', filename='css/libs/bootstrap.min.css')}}">
    <link rel="stylesheet" href="{{url_for('static', filename='css/main.css')}}">

    {% block style %} {% endblock %}

    <title>{% block title %}Base{% endblock %}</title>
</head>


<body>
    
    <div class="page">

    <header class="header"> {% include 'main/_header.html' %} </header>

    

    <main class="content">
        {% include 'main/_flash.html' %}
        {% block page_title %}  {% endblock %}
        {% block content %} Base content  {% endblock %}
    </main>
    <footer class="py-3 my-4"> {% include 'main/_footer.html' %} </footer>
    </div>
    
    
    <script src="{{ url_for('static', filename='js/libs/bootstrap.min.js')}}"></script>
    <script src="{{ url_for('static', filename='js/app.js')}}"></script>
</body>

</html>

app/templates/post/all.html
{% extends 'main/base.html' %} 

{% block page_title %} Все темы таблица {% endblock %}

{% block style %} 
<link rel="stylesheet"
      href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/all.min.css">
<link rel="stylesheet" href="{{ url_for('static', filename='css/blocks/table.css') }}"> 

{% endblock %}

{% block content %}
<div class="table-responsive custom-table-responsive">
<!-- <table class="table-responsive custom-table-responsive"> -->
<table class="table custom-talble">
    <thead>
        <tr>
            <th scope="col">Преподаватель</th>
            <th scope="col">Предмет</th>
            <th scope="col">Студент</th>
            <th scope="col">Действие</th>

        </tr>
    </thead>
    <tbody>
        {% for post in posts %}
        <tr scope="row">
            <td>{{ post.teacher }}</td>
            <td>{{ post.subject }}</td>
            <td>{{ post.student }}</td>
            <td>
                <a href="{{ url_for('post.update', id=post.id) }}" class="btn btn-sm btn-secondary"><span class="fa-solid fa-pen-to-square"></span></a>
                <a href="{{ url_for('post.delete', id=post.id) }}" class="btn btn-sm btn-danger"><span class="fa-solid fa-trash"></span></a>
            </td>
        </tr>
        {% endfor %}
    </tbody>
</table>
</div>
{% endblock %}

app/templates/post/create.html
{% extends 'main/base.html' %} 

{% block page_title %} Добавление темы {% endblock %}

{% block content %}
<form method="post" class="form-control d-flex flex-column gap-2">
    <input name="teacher" type="text" placeholder="ФИО преподавателя" class="form-control">
    <input name="subject" type="text" placeholder="Тема" class="form-control">
    <input name="student" type="text" placeholder="ФИО студента" class="form-control">
    <input value="Добавить" type="submit" class="btn btn-success">
</form>
{% endblock %}

app/templates/post/update.html
{% extends 'main/base.html' %} 

{% block page_title %} Редактирование темы {{ post.id }} {% endblock %}

{% block content %}
<form method="post" class="form-control d-flex flex-column gap-2">
    <input value="{{ post.teacher }}" name="teacher" type="text" placeholder="ФИО преподавателя" class="form-control">
    <input value="{{ post.subject }}" name="subject" type="text" placeholder="Тема" class="form-control">
    <input value="{{ post.student }}" name="student" type="text" placeholder="ФИО студента" class="form-control">
    <input value="Обновить" type="submit" class="btn btn-success">
</form> 
{% endblock %}

app/templates/user/login.html
{% extends 'main/base.html' %} 

{% block page_title %} Авторизация {% endblock %}


{% block content %}

    <form method="post" class="form-control d-flex flex-column gap-2">
        {{ form.csrf_token }}
        {{ form.login(class='form-control', placeholder='Login') }}
        {{ form.password(class='form-control', placeholder='Password') }}
        {{ form.remember(class='form-control') }}
        {{ form.submit(class='btn btn-success') }}
    </form>

{% endblock  %}

app/templates/user/register.html
{% extends 'main/base.html' %} 

{% block page_title %} Регистрация {% endblock %}


{% block content %}

    <form method="post" enctype="multipart/form-data" class="form-control d-flex flex-column gap-2">
        {{ form.csrf_token }}
        {{ form.name(class='form-control', placeholder="FIO") }}
        
        
        {{ form.login(class='form-control', placeholder='Login') }}
        {% if form.login.errors %}
            <div class="invalid-feedback" style="display: block!important;">
                {% for error in form.login.errors %}
                    <span>{{ error }}</span>
                {% endfor %}
            </div>
        {% endif %}

        {{ form.avatar(class='form-control') }}
        {{ form.password(class='form-control', placeholder='Password') }}
        {{ form.confirm_password(class='form-control', placeholder='Confirm') }}
        {{ form.submit(class='btn btn-success') }}
    </form>

{% endblock  %}